services:
  biogateway:
    build: 
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - biomysql
    networks:
      - bio-network

  biofpm:
    build: 
      context: .
      dockerfile: docker/fpm.Dockerfile
    env_file:
      - .env
    depends_on:
      - biomysql
    networks:
      - bio-network
    volumes:
      - ./web:/var/www

  biomysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - bio-network
    env_file:
      - .env
    volumes:
      - ./docker/vars/mysql/1_create_user.sh:/docker-entrypoint-initdb.d/1_create_user.sh
      - ./docker/vars/mysql/2_init_db.sh:/docker-entrypoint-initdb.d/2_init_db.sh
      - ./dbdata:/var/lib/mysql

  biodns:
    build: 
      context: .
      dockerfile: docker/dns.Dockerfile
      args:
        - SERVER_IP=${SERVER_IP}
        - ROUTER_IP=${ROUTER_IP}
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN


networks:
  bio-network:
    driver: bridge
    name: bio-network
